const $=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM '+Number(n||0).toLocaleString('en-MY',{maximumFractionDigits:0});
let listings=[],selected=new Set();
const photos=x=>x.photos?.length?x.photos:(x.photo?[x.photo]:[]);
const type=x=>x.title||[x.propertySubtype,x.propertyType].filter(v=>v&&v!=='Not Applicable').join(' ')||'Property';
const usable=v=>v&&v!=='N/A'&&v!=='Not Specified'&&v!=='Not Applicable';
function card(x){const p=photos(x)[0],id=esc(x.id),facts=[x.bedrooms&&`${x.bedrooms} Beds`,x.bathrooms&&`${x.bathrooms} Baths`,x.landSize&&`${Number(x.landSize).toLocaleString()} sqft`].filter(usable).join(' · ');return `<article class="listing-card" onclick="showDetail('${id}')"><label class="pick" onclick="event.stopPropagation()"><input type="checkbox" ${selected.has(String(x.id))?'checked':''} onchange="toggleListing('${id}',this.checked)"><span>Select</span></label>${p?`<img src="${p}" alt="${esc(type(x))}" loading="lazy">`:'<div class="placeholder">⌂</div>'}<div class="card-body"><small>${esc(x.deal||'Listing')}</small><strong>${money(x.price)}</strong><h2>${esc(x.location||'Melaka')}</h2><p>${esc(type(x))}</p>${facts?`<span>${esc(facts)}</span>`:''}</div></article>`}
function render(){const q=$('#search').value.trim().toLowerCase(),rows=listings.filter(x=>!q||[x.location,type(x),x.tenure,x.price,x.deal].some(v=>String(v||'').toLowerCase().includes(q)));$('#count').textContent=`${rows.length} listing${rows.length===1?'':'s'}`;$('#list').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No matching listings.</div>'}
window.toggleListing=(id,on)=>{on?selected.add(String(id)):selected.delete(String(id));$('#selectedCount').textContent=selected.size;$('#selectionBar').classList.toggle('hidden',!selected.size);render()};
window.showDetail=id=>{const x=listings.find(v=>String(v.id)===String(id));if(!x)return;const pics=photos(x),facts=[['Property',type(x)],['Tenure',x.tenure],['Land size',x.landSize&&`${Number(x.landSize).toLocaleString()} sqft`],['Built-up',x.builtUp&&`${Number(x.builtUp).toLocaleString()} sqft`],['Bedrooms',x.bedrooms],['Bathrooms',x.bathrooms],['Car parks',x.carParks],['Lot type',x.lotType],['Furnishing',x.furnishing],['Renovation',x.renovation]].filter(([,v])=>usable(v));$('#detail').innerHTML=`<button class="close" onclick="document.querySelector('#detailDialog').close()">×</button>${pics.length?`<div class="gallery">${pics.map(p=>`<img src="${p}" alt="${esc(type(x))}">`).join('')}</div>`:'<div class="detail-placeholder">⌂</div>'}<div class="detail-body"><small>${esc(x.deal||'Listing')}</small><h2>${esc(x.location||'Melaka')}</h2><strong>${money(x.price)}</strong><div class="facts">${facts.map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join('')}</div><button class="select-detail" onclick="toggleListing('${esc(x.id)}',true);document.querySelector('#detailDialog').close()">Select this property</button></div>`;$('#detailDialog').showModal()};
$('#search').oninput=render;
$('#whatsappBtn').onclick=()=>{const chosen=listings.filter(x=>selected.has(String(x.id))),lines=chosen.map((x,i)=>`${i+1}. ${x.location||'Melaka'} — ${type(x)} — ${money(x.price)}`);const message=`Hi Tong Xen, I am interested in these properties:\n\n${lines.join('\n')}\n\nPlease send me more details / arrange viewing.\n${location.href}`;location.href=`https://wa.me/60166286918?text=${encodeURIComponent(message)}`};
(async()=>{const agent=new URLSearchParams(location.search).get('agent');try{if(!agent)throw Error();const r=await fetch(`/api/catalog/${encodeURIComponent(agent)}`,{cache:'no-store'});if(!r.ok)throw Error();listings=(await r.json()).listings||[];render()}catch{$('#count').textContent='';$('#list').innerHTML='<div class="empty">This property catalog is unavailable.</div>'}})();
