const $=s=>document.querySelector(s),esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM '+Number(n||0).toLocaleString('en-MY',{maximumFractionDigits:0});
let listings=[],selected=new Set();
const photos=x=>x.photos?.length?x.photos:(x.photo?[x.photo]:[]);
const type=x=>x.title||[x.propertySubtype,x.propertyType].filter(v=>v&&v!=='Not Applicable').join(' ')||'Property';
const usable=v=>v&&v!=='N/A'&&v!=='Not Specified'&&v!=='Not Applicable';
function card(x){const pics=photos(x),p=pics[0],id=esc(x.id),facts=[x.bedrooms&&`⌂ ${x.bedrooms} Beds`,x.bathrooms&&`◫ ${x.bathrooms} Baths`,x.landSize&&`◇ ${Number(x.landSize).toLocaleString()} sqft`].filter(usable);return `<article class="listing-card" onclick="showDetail('${id}')"><div class="card-media"><span class="deal-tag">${esc(x.deal||'Listing')}</span><label class="pick" title="Save property" onclick="event.stopPropagation()"><input type="checkbox" ${selected.has(String(x.id))?'checked':''} onchange="toggleListing('${id}',this.checked)"><span>Select</span></label>${p?`<img src="${p}" alt="${esc(type(x))}" loading="lazy">`:'<div class="placeholder">⌂</div>'}${pics.length>1?`<span class="photo-count">▣ ${pics.length} photos</span>`:''}</div><div class="card-body"><div class="card-location">⌖ ${esc(x.location||'Melaka')}</div><strong>${money(x.price)}</strong><h2>${esc(type(x))}</h2>${facts.length?`<div class="card-facts">${facts.map(v=>`<span>${esc(v)}</span>`).join('')}</div>`:''}</div></article>`}
function render(){const q=$('#search').value.trim().toLowerCase(),deal=$('#dealFilter').value,rows=listings.filter(x=>(!q||[x.location,type(x),x.tenure,x.price,x.deal].some(v=>String(v||'').toLowerCase().includes(q)))&&(!deal||String(x.deal||'').toLowerCase().includes(deal)));$('#count').textContent=`${rows.length} propert${rows.length===1?'y':'ies'}`;$('#list').innerHTML=rows.length?rows.map(card).join(''):'<div class="empty">No matching properties found.<br>Try another location or property type.</div>'}
window.toggleListing=(id,on)=>{on?selected.add(String(id)):selected.delete(String(id));$('#selectedCount').textContent=selected.size;$('#selectionBar').classList.toggle('hidden',!selected.size);render()};
window.showDetail=id=>{const x=listings.find(v=>String(v.id)===String(id));if(!x)return;const pics=photos(x),facts=[['Property',type(x)],['Tenure',x.tenure],['Land size',x.landSize&&`${Number(x.landSize).toLocaleString()} sqft`],['Built-up',x.builtUp&&`${Number(x.builtUp).toLocaleString()} sqft`],['Bedrooms',x.bedrooms],['Bathrooms',x.bathrooms],['Car parks',x.carParks],['Lot type',x.lotType],['Furnishing',x.furnishing],['Renovation',x.renovation]].filter(([,v])=>usable(v));$('#detail').innerHTML=`<button class="close" onclick="document.querySelector('#detailDialog').close()">×</button>${pics.length?`<div class="gallery">${pics.map(p=>`<img src="${p}" alt="${esc(type(x))}">`).join('')}</div>`:'<div class="detail-placeholder">⌂</div>'}<div class="detail-body"><div class="detail-top"><div><small>${esc(x.deal||'Listing')}</small><h2>${esc(x.location||'Melaka')}</h2><span>${esc(type(x))}</span></div><strong class="detail-price">${money(x.price)}</strong></div><div class="facts">${facts.map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join('')}</div><button class="select-detail" onclick="toggleListing('${esc(x.id)}',true);document.querySelector('#detailDialog').close()">♡ Add to my favourites</button></div>`;$('#detailDialog').showModal()};
$('#search').oninput=render;
$('#dealFilter').onchange=render;
$('#clearBtn').onclick=()=>{selected.clear();$('#selectionBar').classList.add('hidden');render()};
$('#whatsappBtn').onclick=()=>{const chosen=listings.filter(x=>selected.has(String(x.id))),lines=chosen.map((x,i)=>`${i+1}. ${x.location||'Melaka'} — ${type(x)} — ${money(x.price)}`);const message=`Hi Tong Xen, I am interested in these properties:\n\n${lines.join('\n')}\n\nPlease send me more details / arrange viewing.\n${location.href}`;location.href=`https://wa.me/60166286918?text=${encodeURIComponent(message)}`};
(async()=>{const q=new URLSearchParams(location.search),agent=q.get('agent'),id=q.get('id');try{if(agent){const r=await fetch(`/api/catalog/${encodeURIComponent(agent)}`,{cache:'no-store'});if(!r.ok)throw Error();listings=(await r.json()).listings||[]}else if(id){const rows=await sbJson(`/rest/v1/public_shares?id=eq.${encodeURIComponent(id)}&select=payload`),payload=rows[0]?.payload;if(!payload?.collection)throw Error();listings=payload.listings||[]}else throw Error();render()}catch{$('#count').textContent='';$('#list').innerHTML='<div class="empty">This property catalog is unavailable.</div>'}})();
