(()=>{'use strict';
const $=s=>document.querySelector(s),agent=new URLSearchParams(location.search).get('agent'),state={rows:[],cursor:null,loading:false};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const title=x=>x.title||[x.propertySubtype,x.propertyType].filter(Boolean).join(' ')||'Property listing';
const money=value=>Number.isFinite(Number(value))?'RM '+Number(value).toLocaleString('en-MY',{maximumFractionDigits:0}):'Price on request';
async function api(path){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(path,{signal:controller.signal,headers:{Accept:'application/json'}});let data;try{data=await response.json()}catch{throw Error('unavailable')}if(!response.ok)throw Error(data.error||'unavailable');return data}finally{clearTimeout(timer)}}
function card(x){const image=x.cover||x.photos?.[0],facts=[x.bedrooms&&`${x.bedrooms} beds`,x.bathrooms&&`${x.bathrooms} baths`,x.landSize&&`${x.landSize} sqft`].filter(Boolean);return `<button class="card" data-id="${esc(x.id)}"><div class="media">${image?`<img src="${esc(image)}" alt="" loading="lazy">`:'⌂'}<span class="tag">${esc(x.deal||'Available')}</span></div><div class="body"><small>${esc(x.location||'Location on request')}</small><h3>${esc(title(x))}</h3><div class="price">${esc(money(x.price))}</div>${facts.length?`<div class="facts">${facts.map(esc).join('<span>·</span>')}</div>`:''}</div></button>`}
function filtered(){const query=$('#search').value.trim().toLowerCase(),location=$('#location').value,type=$('#type').value,tenure=$('#tenure').value,[low,high]=($('#price').value||'-').split('-').map(Number);return state.rows.filter(x=>(!query||[title(x),x.location,x.deal].join(' ').toLowerCase().includes(query))&&(!location||x.location===location)&&(!type||x.propertyType===type)&&(!tenure||x.tenure===tenure)&&(!$('#price').value||(Number(x.price)>=low&&Number(x.price)<=high)))}
function render(){const rows=filtered();$('#grid').innerHTML=rows.length?rows.map(card).join(''):'<div class="state">No properties match these filters.</div>';$('#count').textContent=`${rows.length} shown`;$('#more').hidden=!state.cursor}
function addOptions(id,values){const select=$(id),current=new Set([...select.options].map(x=>x.value));[...new Set(values.filter(Boolean))].sort().forEach(value=>{if(!current.has(String(value)))select.add(new Option(value,value))})}
async function load(){if(state.loading||!agent)return;state.loading=true;$('#more').disabled=true;try{const query=new URLSearchParams({agent,limit:'24'});if(state.cursor)query.set('cursor',state.cursor);const data=await api('/api/public/catalog?'+query);state.rows.push(...data.listings);state.cursor=data.nextCursor;addOptions('#location',state.rows.map(x=>x.location));addOptions('#type',state.rows.map(x=>x.propertyType));addOptions('#tenure',state.rows.map(x=>x.tenure));render()}catch{$('#grid').innerHTML='<div class="state error">We could not load this collection. Please try again shortly.</div>';$('#more').hidden=true}finally{state.loading=false;$('#more').disabled=false}}
async function detail(id){const dialog=$('#dialog');$('#detail').innerHTML='<div class="state"><span class="spinner"></span>Loading details…</div>';dialog.showModal();try{const {listing:x}=await api(`/api/public/catalog/${encodeURIComponent(id)}?agent=${encodeURIComponent(agent)}`),image=x.photos?.[0],facts=[['Property type',x.propertyType],['Tenure',x.tenure],['Land size',x.landSize],['Built-up',x.builtUp],['Bedrooms',x.bedrooms],['Bathrooms',x.bathrooms],['Car parks',x.carParks],['Furnishing',x.furnishing],['Title',x.titleType]].filter(([,v])=>v!==undefined&&v!==null&&v!=='');$('#detail').innerHTML=`${image?`<img class="detail-photo" src="${esc(image)}" alt="${esc(title(x))}">`:''}<div class="detail-copy"><small>${esc(x.location||'')}</small><h2>${esc(title(x))}</h2><div class="price">${esc(money(x.price))}</div><div class="detail-grid">${facts.map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join('')}</div><a class="whatsapp" target="_blank" rel="noopener" href="https://wa.me/60166286918?text=${encodeURIComponent(`Hi, I am interested in ${title(x)} (${x.id}).`)}">Ask about this property</a></div>`}catch{$('#detail').innerHTML='<div class="state error">This listing is temporarily unavailable.</div>'}}
$('#grid').addEventListener('click',event=>{const item=event.target.closest('[data-id]');if(item)detail(item.dataset.id)});$('#more').onclick=load;$('#dialog .close').onclick=()=>$('#dialog').close();['#search','#location','#type','#tenure','#price'].forEach(id=>$(id).addEventListener(id==='#search'?'input':'change',render));
if(!agent||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(agent)){$('#grid').innerHTML='<div class="state error">This catalog link is invalid.</div>'}else load();
})();
