(() => {
 const joinForm=document.querySelector('#joinMemberForm');
 if(joinForm){
  const status=document.querySelector('#joinStatus'),token=new URLSearchParams(location.hash.slice(1)).get('invite')||'';
  const request=async(path,body)=>{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(30000)});const data=await r.json();if(!r.ok)throw Error(data.error||'Invitation unavailable');return data};
  if(!/^[0-9a-f]{64}$/.test(token)){status.textContent='This invitation link is invalid. Ask Tong Xen for a new link.';return}
  request('/api/member-invites/check',{token}).then(data=>{joinForm.hidden=false;status.textContent='Invitation available until '+new Date(data.expires_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'})+' (Malaysia time).'}).catch(e=>{status.textContent=e.message});
  joinForm.onsubmit=async e=>{e.preventDefault();const button=joinForm.querySelector('button');button.disabled=true;status.textContent='Sending your invitation…';try{const data=await request('/api/member-invites/join',{token,name:joinForm.elements.name.value.trim(),email:joinForm.elements.email.value.trim()});joinForm.hidden=true;status.textContent=data.message;history.replaceState(null,'',location.pathname)}catch(err){status.textContent=err.message;button.disabled=false}};
  return;
 }
 const form=document.querySelector('#createInviteLinkForm');if(!form)return;
 const status=document.querySelector('#inviteLinkStatus'),output=document.querySelector('#inviteLinkOutput'),input=document.querySelector('#memberInviteLink'),historyList=document.querySelector('#inviteLinkHistory');
 const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let request=0,activeLinkId=null;
 async function refresh(){const current=++request,user=session?.user.id;if(!session||!isAdmin){historyList.textContent='';return}try{const rows=await sbJson('/rest/v1/rpc/list_workspace_invite_links',{method:'POST',token:session.access_token,body:'{}'});if(current!==request||session?.user.id!==user||!isAdmin)return;historyList.innerHTML=rows.length?rows.map(row=>{const active=!row.revoked_at&&new Date(row.expires_at)>new Date()&&row.uses+row.processing<row.max_uses;return `<div class="invite-link-row"><div><b>${row.uses} / ${row.max_uses} members invited</b><small>${row.processing?'Processing / reserved: '+row.processing+' · ':''}${row.revoked_at?'Revoked':new Date(row.expires_at)<=new Date()?'Expired':active?'Available':'Fully reserved or used'} · Expires ${escape(new Date(row.expires_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'}))} MYT</small></div>${!row.revoked_at&&new Date(row.expires_at)>new Date()?`<button type="button" data-revoke-invite="${escape(row.id)}">Revoke link</button>`:''}</div>`}).join(''):'<p>No invitation links yet.</p>'}catch(e){historyList.textContent='Unable to load invitations. '+e.message}}
 form.onsubmit=async e=>{e.preventDefault();if(!session||!isAdmin)return;const user=session.user.id,button=e.submitter;button.disabled=true;status.textContent='Creating invitation link…';output.hidden=true;input.value='';try{const data=await sbJson('/rest/v1/rpc/create_workspace_invite_link',{method:'POST',token:session.access_token,body:JSON.stringify({valid_days:Number(form.elements.days.value),member_limit:Number(form.elements.members.value)})});if(session?.user.id!==user||!isAdmin)return;activeLinkId=data.id;input.value=location.origin+'/join.html#invite='+data.token;output.hidden=false;status.textContent=`Valid for ${data.max_uses} member${data.max_uses===1?'':'s'} until ${new Date(data.expires_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'})} MYT. Copy the link now; the full link is not stored.`;await refresh()}catch(err){status.textContent=err.message}finally{button.disabled=false}};
 document.querySelector('#copyMemberInvite').onclick=async()=>{try{await navigator.clipboard.writeText(input.value);status.textContent='Copied. Share this link privately with the member you want to invite.'}catch{input.focus();input.select();status.textContent='Select and copy the invitation link.'}};
 historyList.onclick=async e=>{const button=e.target.closest('button[data-revoke-invite]');if(!button||!session||!isAdmin)return;button.disabled=true;try{await sbJson('/rest/v1/rpc/revoke_workspace_invite_link',{method:'POST',token:session.access_token,body:JSON.stringify({invitation_id:button.dataset.revokeInvite})});if(button.dataset.revokeInvite===activeLinkId){input.value='';output.hidden=true;activeLinkId=null}await refresh();status.textContent='Link revoked. Existing members remain managed in the account list.'}catch(err){status.textContent=err.message;button.disabled=false}};
 document.querySelector('#refreshInviteLinks').onclick=refresh;
 document.querySelector('#inviteLinkHistoryPanel').addEventListener('toggle',e=>{if(e.currentTarget.open)void refresh()});
 new MutationObserver(()=>{if(!document.querySelector('#authScreen').classList.contains('ready')){request++;input.value='';output.hidden=true;status.textContent='';historyList.innerHTML=''}}).observe(document.querySelector('#authScreen'),{attributes:true,attributeFilter:['class']});
})();
