const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM '+Number(n||0).toLocaleString('en-MY',{maximumFractionDigits:0});
const photos=x=>x.photos?.length?x.photos:(x.photo?[x.photo]:[]),na=v=>v&&v!=='N/A'&&v!=='Not Specified'&&v!=='Not Applicable';
const propertySubtype=x=>x.propertySubtype||x.storeys||'';
const preferredSize=x=>na(x.landSize)?['Land',x.landSize]:na(x.builtUp)?['Built-up',x.builtUp]:null;
let activePhotos=[],activePhotoIndex=0;
function monthly(price){const L=+price*.9,r=.038/12,n=35*12;return L*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)}
function age(v){if(!v)return'';const d=Math.max(0,Math.floor((Date.now()-new Date(v))/86400000));return d===0?'Updated today':`Updated ${d} day${d>1?'s':''} ago`}
function detail(x){const pics=photos(x),type=x.title||x.propertyType||'Property',subtype=propertySubtype(x),rent=x.deal==='For Rent',preferred=preferredSize(x),size=Number(preferred?.[1]||0),psf=size&&x.price?Math.round(+x.price/size):0,wa=`https://wa.me/60166286918?text=${encodeURIComponent('Hi Tong Xen, I am interested in '+type+' at '+x.location)}`;activePhotos=pics;activePhotoIndex=0;document.title=`${type} · ${x.location||'Melaka'}`;const sizeFact=preferred&&[Number(preferred[1]).toLocaleString()+' sqft',preferred[0],'◇'],facts=[[x.bedrooms,'Bedrooms','⌂'],[x.bathrooms,'Bathrooms','◫'],sizeFact].filter(v=>v&&na(v[0]));return `<header class="hero"><button class="back-button" onclick="goBack()" aria-label="返回上一页">‹</button><small>${esc(x.deal||'Property Listing')}</small><h1>${esc(type)}</h1><div>${esc(x.location)}</div><p class="price">${money(x.price)}${rent?' / month':''}</p>${psf?`<span class="psf">RM ${psf.toLocaleString()} psf</span>`:''}${age(x.updatedAt)?`<span class="updated">${age(x.updatedAt)}</span>`:''}</header>${pics.length?`<div class="gallery"><img id="mainPhoto" src="${pics[0]}" alt="${esc(type)}">${pics.length>1?`<button class="gallery-arrow prev" onclick="changePhoto(-1)" aria-label="Previous photo">‹</button><button class="gallery-arrow next" onclick="changePhoto(1)" aria-label="Next photo">›</button>`:''}<span class="photo-count">1 / ${pics.length}</span></div>`:'<div class="no-photo">⌂<small>Photos available on request</small></div>'}<section class="content"><div class="key-facts">${facts.map(v=>`<div><i>${v[2]}</i><b>${esc(v[0])}</b><small>${v[1]}</small></div>`).join('')}</div><div class="chips">${[x.tenure,x.leaseYears&&x.leaseYears+' yrs remaining',x.leaseExpiry&&'Lease until '+x.leaseExpiry,x.lotType,subtype,x.furnishing,x.renovation].filter(na).map(v=>`<span>${esc(v)}</span>`).join('')}</div><div class="details">${[['Property type',x.propertyType],['Property subtype',subtype],preferred&&[preferred[0]==='Land'?'Land size':'Built-up',Number(preferred[1]).toLocaleString()+' sq ft'],['Car parks',x.carParks],['Tenure',x.tenure],['Lease expiry',x.leaseExpiry],['Furnishing',x.furnishing],['Renovation',x.renovation],['Title type',x.titleType],['Land title',x.landTitle],['Bumi lot',x.bumiLot],['Facing',x.facing]].filter(v=>v&&na(v[1])).map(v=>`<div class="detail"><small>${v[0]}</small><b>${esc(v[1])}</b></div>`).join('')}</div>${!rent?`<div class="loan"><small>Estimated monthly instalment</small><strong>${money(monthly(x.price))}</strong><span>90% loan · 3.8% p.a. · 35 years</span></div>`:''}<a class="contact" href="${wa}">WhatsApp for viewing / enquiry</a><p class="agent">Tong Xen [REN 51905] · 016-628 6918<br>The Roof Realty Sdn Bhd E(1)1605/5</p></section><div class="sticky-cta"><button onclick="sharePage()">Share</button><a href="${wa}">WhatsApp Tong Xen</a></div>`}
function collection(x,id){document.title=`${x.listings.length} Property Listings`;return `<header class="collection-head"><small>SELECTED FOR ${esc(x.clientName||'YOU')}</small><h1>${x.listings.length} Property Listings</h1><div>Tap any property to view full details</div></header><section class="collection-list">${x.listings.map((v,i)=>{const p=photos(v)[0],type=v.title||v.propertyType||'Property';return `<a class="collection-card" href="share.html?id=${encodeURIComponent(id)}&item=${i}">${p?`<img src="${p}" alt="${esc(type)}">`:'<span class="placeholder">⌂</span>'}<div><h2>${esc(type)}</h2><p>${esc(v.location)} · ${esc(v.tenure)}</p><b>${money(v.price)}</b></div><i>›</i></a>`}).join('')}</section>`}
window.changePhoto=step=>{if(activePhotos.length<2)return;activePhotoIndex=(activePhotoIndex+step+activePhotos.length)%activePhotos.length;document.querySelector('#mainPhoto').src=activePhotos[activePhotoIndex];document.querySelector('.photo-count').textContent=`${activePhotoIndex+1} / ${activePhotos.length}`};
window.goBack=()=>{if(history.length>1)history.back();else location.href='/'};
window.sharePage=async()=>{if(navigator.share)await navigator.share({title:document.title,url:location.href});else{await navigator.clipboard.writeText(location.href);alert('Link copied')}};
(async()=>{const q=new URLSearchParams(location.search),id=q.get('id'),root=document.querySelector('#listing');try{if(!id)throw Error();const rows=await sbJson(`/rest/v1/public_shares?id=eq.${encodeURIComponent(id)}&select=payload`),x=rows[0]?.payload,item=q.get('item');if(!x)throw Error();root.innerHTML=x.collection?(item!==null?detail(x.listings[Number(item)]):collection(x,id)):detail(x)}catch(e){root.innerHTML='<div class="error">This listing link is unavailable.</div>'}})();
