const C='mari-property-v55',FILES=['./','index.html','styles.css?v=43','site-analytics.css?v=1','cases.css','photos.css?v=17','supabase.js?v=4','app.js?v=60','listing-locations.js?v=1','site-analytics.js?v=1','share.html','share.css?v=19','share.js?v=22','manifest.webmanifest','icons/icon-source.jpg'];
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(C).then(c=>c.addAll(FILES)))});
self.addEventListener('activate',e=>e.waitUntil((async()=>{
 await caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==C).map(k=>caches.delete(k))));
 await self.clients.claim();
})()));
function openShareDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('mari-share-target',1);req.onupgradeneeded=()=>req.result.createObjectStore('shares');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function saveShare(payload){const db=await openShareDB();return new Promise((resolve,reject)=>{const tx=db.transaction('shares','readwrite');tx.objectStore('shares').put(payload,'latest');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
self.addEventListener('fetch',e=>{const url=new URL(e.request.url);if(e.request.method==='POST'&&url.pathname.endsWith('/share-target')){e.respondWith((async()=>{const form=await e.request.formData(),files=form.getAll('photos').filter(x=>x instanceof File&&x.size),text=[form.get('title'),form.get('text'),form.get('url')].filter(Boolean).join('\n');await saveShare({text,files,receivedAt:Date.now()});return Response.redirect(new URL('./?shared=1',e.request.url),303)})());return}if(url.origin!==self.location.origin||url.pathname.startsWith('/api/')||e.request.method!=='GET'||e.request.headers.has('Authorization'))return;if(e.request.mode==='navigate'){e.respondWith(fetch(e.request).catch(()=>caches.match('./')));return}const allowed=FILES.some(file=>new URL(file,self.location.href).pathname===url.pathname);if(!allowed)return;e.respondWith(fetch(e.request).then(r=>{if(r.ok){const copy=r.clone();caches.open(C).then(c=>c.put(e.request,copy))}return r}).catch(()=>caches.match(e.request))) });

