begin;
do $$ declare r jsonb; token text; rid uuid; member_id uuid:=gen_random_uuid(); email text; other jsonb;
begin
 email:=member_id::text||'@example.invalid';
 perform set_config('request.jwt.claim.sub','6c8e4545-3e89-40e2-b5a9-7a18475641d7',true);
 r:=public.create_workspace_invite_link(7,1);token:=r->>'token';
 if length(token)<>64 or not (public.check_workspace_invite_link(token)->>'valid')::boolean then raise exception 'Link generation failed'; end if;
 if exists(select 1 from public.workspace_invite_links where token_hash=token) then raise exception 'Raw token stored'; end if;
 rid:=public.reserve_workspace_invite(token,email);
 begin perform public.reserve_workspace_invite(token,'another@example.invalid');raise exception 'Quota bypass';exception when invalid_parameter_value then null;end;
 insert into auth.users(id,email,aud,role,invited_at,email_confirmed_at) values(member_id,email,'authenticated','authenticated',now(),now());
 perform public.complete_workspace_invite(rid,member_id);
 perform public.complete_workspace_invite(rid,member_id);
 if (public.check_workspace_invite_link(token)->>'valid')::boolean then raise exception 'Used link remained available'; end if;
 if exists(select 1 from public.admin_users where user_id=member_id) then raise exception 'Invitation promoted admin'; end if;
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 if public.is_admin() or not public.is_workspace_member() then raise exception 'Member role incorrect'; end if;
 begin perform public.create_workspace_invite_link();raise exception 'Member invited accounts';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claim.sub','6c8e4545-3e89-40e2-b5a9-7a18475641d7',true);
 other:=public.create_workspace_invite_link(1,1);rid:=public.reserve_workspace_invite(other->>'token','retry@example.invalid');
 perform public.release_workspace_invite(rid);
 if not (public.check_workspace_invite_link(other->>'token')->>'valid')::boolean then raise exception 'Safe release did not restore place'; end if;
 perform public.revoke_workspace_invite_link((other->>'id')::uuid);
 if (public.check_workspace_invite_link(other->>'token')->>'valid')::boolean then raise exception 'Revoked link usable'; end if;
 other:=public.create_workspace_invite_link(1,5);
 update public.workspace_invite_links set expires_at=now()-interval '1 minute' where id=(other->>'id')::uuid;
 if (public.check_workspace_invite_link(other->>'token')->>'valid')::boolean then raise exception 'Expired link usable'; end if;
 if (public.check_workspace_invite_link('bad')->>'valid')::boolean then raise exception 'Bad token accepted'; end if;
 if has_function_privilege('anon','public.create_workspace_invite_link(integer,integer)','execute') or has_function_privilege('authenticated','public.reserve_workspace_invite(text,text)','execute') then raise exception 'Invitation service leaked to browsers'; end if;
 if has_table_privilege('authenticated','public.workspace_invite_requests','select') or has_table_privilege('anon','public.workspace_invite_links','select') then raise exception 'Invitation data readable'; end if;
end $$;
rollback;
