-- Phase 1 WhatsApp ingestion. Safe to run repeatedly.
create extension if not exists pgcrypto;

create table if not exists public.listing_submissions (
  id uuid primary key default gen_random_uuid(),
  event_type text not null check (event_type in ('messages', 'smb_message_echoes')),
  sender_redacted text not null,
  recipient_redacted text not null,
  started_at timestamptz not null,
  last_activity_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_submission_messages (
  id bigint generated by default as identity primary key,
  listing_submission_id uuid not null references public.listing_submissions(id) on delete cascade,
  meta_message_id text not null unique,
  event_type text not null check (event_type in ('messages', 'smb_message_echoes')),
  message_type text not null,
  message_text text,
  meta_media_id text,
  sender_redacted text not null,
  recipient_redacted text not null,
  message_timestamp timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists listing_submissions_activity_idx
  on public.listing_submissions (sender_redacted, recipient_redacted, event_type, last_activity_at desc);
create index if not exists listing_submission_messages_submission_idx
  on public.listing_submission_messages (listing_submission_id, message_timestamp);

alter table public.listing_submissions enable row level security;
alter table public.listing_submissions force row level security;
alter table public.listing_submission_messages enable row level security;
alter table public.listing_submission_messages force row level security;
revoke all on public.listing_submissions from anon, authenticated;
revoke all on public.listing_submission_messages from anon, authenticated;
revoke all on sequence public.listing_submission_messages_id_seq from anon, authenticated;

create or replace function public.ingest_whatsapp_message(event jsonb)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  submission_id uuid;
  event_time timestamptz;
begin
  if event->>'meta_message_id' is null
     or event->>'event_type' not in ('messages', 'smb_message_echoes')
     or event->>'message_type' is null
     or event->>'sender' is null
     or event->>'recipient' is null then
    raise exception 'invalid WhatsApp event';
  end if;

  event_time := to_timestamp((event->>'timestamp')::double precision);
  perform pg_advisory_xact_lock(hashtextextended(
    event->>'sender' || '|' || event->>'recipient' || '|' || event->>'event_type', 0));

  select m.listing_submission_id into submission_id
    from public.listing_submission_messages m
   where m.meta_message_id = event->>'meta_message_id';
  if submission_id is not null then return submission_id; end if;

  select s.id into submission_id
    from public.listing_submissions s
   where s.sender_redacted = event->>'sender'
     and s.recipient_redacted = event->>'recipient'
     and s.event_type = event->>'event_type'
     and event_time between s.last_activity_at and s.last_activity_at + interval '60 seconds'
   order by s.last_activity_at desc limit 1 for update;

  if submission_id is null then
    insert into public.listing_submissions
      (event_type, sender_redacted, recipient_redacted, started_at, last_activity_at)
    values (event->>'event_type', event->>'sender', event->>'recipient', event_time, event_time)
    returning id into submission_id;
  else
    update public.listing_submissions set last_activity_at = event_time where id = submission_id;
  end if;

  insert into public.listing_submission_messages
    (listing_submission_id, meta_message_id, event_type, message_type, message_text,
     meta_media_id, sender_redacted, recipient_redacted, message_timestamp)
  values
    (submission_id, event->>'meta_message_id', event->>'event_type', event->>'message_type',
     event->>'text', event->>'meta_media_id', event->>'sender', event->>'recipient', event_time)
  on conflict (meta_message_id) do nothing;
  return submission_id;
end;
$$;

revoke all on function public.ingest_whatsapp_message(jsonb) from public, anon, authenticated;
grant execute on function public.ingest_whatsapp_message(jsonb) to service_role;

